/**
 * 水晶数据库
 * image_url 均对应 /images/crystals/ 下的真实文件
 * element 枚举：'Wood'=木, 'Fire'=火, 'Earth'=土, 'Metal'=金, 'Water'=水
 */

const CRYSTAL_DB = [

  // ======== 木属性 (Wood) ========
  {
    id: 1,
    name: '绿玉髓',
    element: 'Wood',
    elementCN: '木',
    chakra: '心轮',
    keywords: ['活力', '生机', '成长'],
    description: '翠绿如嫩芽，饱含蓬勃的木属性生命能量，激发内在潜力，助力事业与健康同步提升。',
    price: 88,
    image_url: '/images/crystals/木/绿玉髓珠子特写.png',
    size_mm: 10,
    stock: 60,
  },
  {
    id: 2,
    name: '东陵玉',
    element: 'Wood',
    elementCN: '木',
    chakra: '心轮',
    keywords: ['平静', '愈合', '新生'],
    description: '淡雅的绿色如同春日新芽，带来平静与疗愈的能量，适合需要重新出发的心灵。',
    price: 48,
    image_url: '/images/crystals/木/东陵玉珠子特写.png',
    size_mm: 10,
    stock: 80,
  },
  {
    id: 3,
    name: '孔雀石',
    element: 'Wood',
    elementCN: '木',
    chakra: '心轮',
    keywords: ['转变', '保护', '蜕变'],
    description: '墨绿纹路如同羽翼展开，是强力的转化之石，帮助突破旧有格局，迎接生命的全新蜕变。',
    price: 128,
    image_url: '/images/crystals/木/孔雀石珠子特写.png',
    size_mm: 10,
    stock: 40,
  },
  {
    id: 4,
    name: '绿草莓晶',
    element: 'Wood',
    elementCN: '木',
    chakra: '心轮',
    keywords: ['爱', '成长', '包容'],
    description: '草莓般的内含物在绿色光芒中闪耀，汇聚木属性的爱与生长能量，滋养心灵，广结善缘。',
    price: 148,
    image_url: '/images/crystals/木/绿草莓晶珠子特写.png',
    size_mm: 10,
    stock: 35,
  },
  {
    id: 5,
    name: '蓝玉髓',
    element: 'Wood',
    elementCN: '木',
    chakra: '喉轮',
    keywords: ['沟通', '平和', '表达'],
    description: '蓝绿相融的柔和色调，同时激活木属性的舒展能量与喉轮的表达之力，让沟通更加温润顺畅。',
    price: 108,
    image_url: '/images/crystals/木/蓝玉髓珠子特写.png',
    size_mm: 10,
    stock: 50,
  },

  // ======== 火属性 (Fire) ========
  {
    id: 6,
    name: '红玉髓',
    element: 'Fire',
    elementCN: '火',
    chakra: '骶轮',
    keywords: ['热情', '创造', '行动'],
    description: '如火焰跳动的橘红色泽，激活创造力与行动力，为踌躇不决的心注入一往无前的勇气。',
    price: 68,
    image_url: '/images/crystals/火/红玉髓珠子特写.png',
    size_mm: 10,
    stock: 75,
  },
  {
    id: 7,
    name: '太阳石',
    element: 'Fire',
    elementCN: '火',
    chakra: '太阳神经丛轮',
    keywords: ['乐观', '领导力', '阳光'],
    description: '携带着太阳的能量，驱散阴霾，带来持续的乐观与行动力，是领导者之石。',
    price: 158,
    image_url: '/images/crystals/火/太阳石珠子特写.png',
    size_mm: 10,
    stock: 30,
  },
  {
    id: 8,
    name: '粉水晶',
    element: 'Fire',
    elementCN: '火',
    chakra: '心轮',
    keywords: ['爱', '吸引力', '自爱'],
    description: '爱与美的象征，散发温柔粉色光芒，吸引美好感情，唤醒内心对自我的深切关爱。',
    price: 78,
    image_url: '/images/crystals/火/粉水晶珠子特写.png',
    size_mm: 10,
    stock: 90,
  },
  {
    id: 9,
    name: '红草莓晶',
    element: 'Fire',
    elementCN: '火',
    chakra: '根轮',
    keywords: ['活力', '热情', '爱情'],
    description: '火焰般的红色中满布天然草莓状内含物，兼具根轮的生命力与心轮的爱，是爱情与活力的双重守护。',
    price: 148,
    image_url: '/images/crystals/火/红草莓晶珠子特写.png',
    size_mm: 10,
    stock: 28,
  },
  {
    id: 10,
    name: '乌拉圭紫水晶',
    element: 'Fire',
    elementCN: '火',
    chakra: '顶轮',
    keywords: ['直觉', '清醒', '专注'],
    description: '来自乌拉圭矿洞的顶级紫水晶，深邃紫色蕴含宇宙智慧，激活第三只眼，在火属性推动下释放洞察力。',
    price: 168,
    image_url: '/images/crystals/火/乌拉圭紫水晶珠子特写.png',
    size_mm: 10,
    stock: 20,
  },
  {
    id: 11,
    name: '紫锂辉',
    element: 'Fire',
    elementCN: '火',
    chakra: '心轮',
    keywords: ['爱', '慈悲', '疗愈'],
    description: '淡紫至玫瑰的温柔渐变，是爱与高频能量之石，帮助敞开心扉，接受并给予无条件的爱。',
    price: 228,
    image_url: '/images/crystals/火/紫锂辉珠子特写.png',
    size_mm: 10,
    stock: 18,
  },
  {
    id: 12,
    name: '紫玉髓',
    element: 'Fire',
    elementCN: '火',
    chakra: '顶轮',
    keywords: ['直觉', '灵性', '智慧'],
    description: '深邃的紫色如暮色苍穹，激活顶轮灵感通道，在火属性的热情驱动下，令直觉与创造力同频共振。',
    price: 108,
    image_url: '/images/crystals/火/紫玉髓珠子特写.png',
    size_mm: 10,
    stock: 45,
  },

  // ======== 土属性 (Earth) ========
  {
    id: 13,
    name: '黄虎眼石',
    element: 'Earth',
    elementCN: '土',
    chakra: '太阳神经丛轮',
    keywords: ['洞察', '专注', '决断'],
    description: '如猛虎之眼，锐利而沉稳，帮助理清思路，做出明智决断，是创业者与决策者的守护石。',
    price: 88,
    image_url: '/images/crystals/土/黄虎眼石珠子特写.png',
    size_mm: 10,
    stock: 55,
  },
  {
    id: 14,
    name: '黄玉髓',
    element: 'Earth',
    elementCN: '土',
    chakra: '太阳神经丛轮',
    keywords: ['财富', '丰盛', '自信'],
    description: '暖阳般的金黄色泽，象征大地的丰饶与富足，提升自我价值感，持续吸引财富与好运。',
    price: 68,
    image_url: '/images/crystals/土/黄玉髓珠子特写.png',
    size_mm: 10,
    stock: 65,
  },
  {
    id: 15,
    name: '金发晶',
    element: 'Earth',
    elementCN: '土',
    chakra: '太阳神经丛轮',
    keywords: ['招财', '事业', '能量'],
    description: '水晶体内的金色发丝如太阳光束穿透大地，是最强力的招财之石，汇聚正向能量，加速事业腾飞。',
    price: 168,
    image_url: '/images/crystals/土/金发晶珠子特写.png',
    size_mm: 10,
    stock: 25,
  },
  {
    id: 16,
    name: '茶水晶',
    element: 'Earth',
    elementCN: '土',
    chakra: '根轮',
    keywords: ['接地', '稳定', '沉静'],
    description: '烟熏般的茶褐色沉淀着大地的稳重，帮助释放负能量，让浮躁的心回归沉稳，牢固根基。',
    price: 88,
    image_url: '/images/crystals/土/茶水晶珠子特写.png',
    size_mm: 10,
    stock: 40,
  },
  {
    id: 17,
    name: '彼得石',
    element: 'Earth',
    elementCN: '土',
    chakra: '太阳神经丛轮',
    keywords: ['变化', '力量', '转型'],
    description: '蓝金交织的闪耀变幻，被称为"变革之石"，在土属性能量的稳固基础上，助力人生的关键转型。',
    price: 188,
    image_url: '/images/crystals/土/彼得石珠子特写.png',
    size_mm: 10,
    stock: 22,
  },

  // ======== 金属性 (Metal) ========
  {
    id: 18,
    name: '白水晶',
    element: 'Metal',
    elementCN: '金',
    chakra: '顶轮',
    keywords: ['净化', '放大', '清晰'],
    description: '水晶之王，具有强大的净化与能量放大效果，可增强其他水晶的能量，清晰思路，开启智慧。',
    price: 58,
    image_url: '/images/crystals/金/白水晶珠子特写.png',
    size_mm: 10,
    stock: 100,
  },
  {
    id: 19,
    name: '喜马拉雅水晶',
    element: 'Metal',
    elementCN: '金',
    chakra: '顶轮',
    keywords: ['高频', '净化', '提升'],
    description: '来自世界屋脊的稀有水晶，千万年雪山能量凝结其中，高频振动净化身心，快速连接宇宙能量。',
    price: 238,
    image_url: '/images/crystals/金/喜马拉雅水晶珠子特写.png',
    size_mm: 10,
    stock: 15,
  },
  {
    id: 20,
    name: '金发晶',
    element: 'Metal',
    elementCN: '金',
    chakra: '顶轮',
    keywords: ['权威', '领导', '招财'],
    description: '金色发丝在白水晶中如阳光穿透云层，兼具金属性的精准与权威，令领导力与财运双重提升。',
    price: 198,
    image_url: '/images/crystals/金/金发晶珠子特写_副本.png',
    size_mm: 10,
    stock: 20,
  },
  {
    id: 21,
    name: '银耀石',
    element: 'Metal',
    elementCN: '金',
    chakra: '眉心轮',
    keywords: ['魔法', '洞察', '变化'],
    description: '闪烁迷幻蓝光的神秘之石，被称为北极光的化身，增强直觉力与灵性感知，引导人生关键转机。',
    price: 198,
    image_url: '/images/crystals/金/银耀石珠子特写.png',
    size_mm: 10,
    stock: 28,
  },

  // ======== 水属性 (Water) ========
  {
    id: 22,
    name: '海蓝宝',
    element: 'Water',
    elementCN: '水',
    chakra: '喉轮',
    keywords: ['沟通', '平静', '诚实'],
    description: '如深邃海洋的宁静，净化思绪，助力清晰表达，带来心灵的平和与安详，是水属性最温柔的守护。',
    price: 238,
    image_url: '/images/crystals/水/海蓝宝珠子特写.png',
    size_mm: 10,
    stock: 25,
  },
  {
    id: 23,
    name: '月光石',
    element: 'Water',
    elementCN: '水',
    chakra: '眉心轮',
    keywords: ['直觉', '女性能量', '新开始'],
    description: '携带月亮的神秘能量，增强直觉与感知力，滋养内在阴柔能量，在新旅程中给予温柔的指引。',
    price: 168,
    image_url: '/images/crystals/水/月光石珠子特写.png',
    size_mm: 10,
    stock: 35,
  },
  {
    id: 24,
    name: '蓝晶石',
    element: 'Water',
    elementCN: '水',
    chakra: '喉轮',
    keywords: ['沟通', '真实', '专注'],
    description: '蓝色晶体如流水般清澈，是天然的能量对齐之石，无需净化即可持续维持高频，助力真实自我的表达。',
    price: 148,
    image_url: '/images/crystals/水/蓝晶石珠子特写.png',
    size_mm: 10,
    stock: 38,
  },
  {
    id: 25,
    name: '蓝虎眼石',
    element: 'Water',
    elementCN: '水',
    chakra: '喉轮',
    keywords: ['洞察', '冷静', '清醒'],
    description: '深邃的蓝灰色泽赋予使用者冷静的洞察力，水属性的流动智慧助其在复杂局势中看清本质、从容应对。',
    price: 98,
    image_url: '/images/crystals/水/蓝虎眼石珠子特写.png',
    size_mm: 10,
    stock: 42,
  },
  {
    id: 26,
    name: '黑曜石',
    element: 'Water',
    elementCN: '水',
    chakra: '根轮',
    keywords: ['保护', '辟邪', '接地'],
    description: '火山熔岩急速冷却的产物，具有强大的保护能量，阻挡外来负能量，清除内心的阴暗面，令心神安定。',
    price: 48,
    image_url: '/images/crystals/水/黑曜石珠子特写.png',
    size_mm: 10,
    stock: 100,
  },
  {
    id: 27,
    name: '黑玛瑙',
    element: 'Water',
    elementCN: '水',
    chakra: '根轮',
    keywords: ['稳定', '保护', '耐力'],
    description: '深邃的黑色如夜空般包容一切，强化意志力与耐力，守护佩戴者免受负面情绪与外界压力的干扰。',
    price: 68,
    image_url: '/images/crystals/水/黑玛瑙珠子特写.png',
    size_mm: 10,
    stock: 80,
  },
  {
    id: 28,
    name: '金运石',
    element: 'Water',
    elementCN: '水',
    chakra: '心轮',
    keywords: ['好运', '财运', '机遇'],
    description: '绿色光泽中透着金色的灵动，是招引好运与财气的幸运之石，开启意想不到的机遇之门。',
    price: 118,
    image_url: '/images/crystals/水/金运石珠子特写.png',
    size_mm: 10,
    stock: 50,
  },
  {
    id: 29,
    name: '黑发晶',
    element: 'Water',
    elementCN: '水',
    chakra: '根轮',
    keywords: ['辟邪', '净化', '防护'],
    description: '黑色电气石发丝贯穿水晶，形成双重防护壁垒，强力阻隔负能量，同时净化自身能量场。',
    price: 138,
    image_url: '/images/crystals/水/黑发晶珠子特写.png',
    size_mm: 10,
    stock: 30,
  },

  // ======== 香灰琉璃系列 ========
  {
    id: 30,
    name: '绿香灰琉璃',
    element: 'Wood',
    elementCN: '木',
    chakra: '心轮',
    keywords: ['禅意', '生机', '净化'],
    description: '以寺院香灰烧制而成的琉璃珠，绿色寓意生机与木属性的蓬勃能量，兼具禅意与现代美感，净化身心。',
    price: 58,
    image_url: '/images/crystals/木/绿香灰琉璃.png',
    size_mm: 10,
    stock: 60,
  },
  {
    id: 31,
    name: '红香灰琉璃',
    element: 'Fire',
    elementCN: '火',
    chakra: '根轮',
    keywords: ['禅意', '热情', '守护'],
    description: '以寺院香灰烧制而成的琉璃珠，红色汇聚火属性的热情与守护能量，沉淀香火功德，护持平安。',
    price: 58,
    image_url: '/images/crystals/火/红香灰琉璃.png',
    size_mm: 10,
    stock: 60,
  },
  {
    id: 32,
    name: '白香灰琉璃',
    element: 'Metal',
    elementCN: '金',
    chakra: '顶轮',
    keywords: ['禅意', '净化', '清明'],
    description: '以寺院香灰烧制而成的琉璃珠，白色契合金属性的清澈本质，净化思绪，引导内心回归清明平静。',
    price: 58,
    image_url: '/images/crystals/金/白香灰琉璃.png',
    size_mm: 10,
    stock: 60,
  },
  {
    id: 33,
    name: '黄香灰琉璃',
    element: 'Earth',
    elementCN: '土',
    chakra: '太阳神经丛轮',
    keywords: ['禅意', '丰盛', '稳定'],
    description: '以寺院香灰烧制而成的琉璃珠，黄色承载土属性的丰盛与稳定，功德加持，招引财运与平安。',
    price: 58,
    image_url: '/images/crystals/土/黄香灰琉璃.png',
    size_mm: 10,
    stock: 60,
  },
  {
    id: 34,
    name: '黑香灰琉璃',
    element: 'Water',
    elementCN: '水',
    chakra: '根轮',
    keywords: ['禅意', '保护', '沉静'],
    description: '以寺院香灰烧制而成的琉璃珠，黑色蕴含水属性的深沉与保护之力，阻挡负能量，令心神沉静安定。',
    price: 58,
    image_url: '/images/crystals/水/黑香灰琉璃.png',
    size_mm: 10,
    stock: 60,
  },

  // ======== 补充品种 ========
  {
    id: 35,
    name: '紫莹石',
    element: 'Fire',
    elementCN: '火',
    chakra: '顶轮',
    keywords: ['专注', '清醒', '灵感'],
    description: '深邃的紫色萤石晶莹剔透，在火属性的激活下开启顶轮通道，扫除思维混沌，令灵感与专注同时迸发。',
    price: 118,
    image_url: '/images/crystals/火/紫莹石单珠特写.png',
    size_mm: 10,
    stock: 35,
  },
  {
    id: 36,
    name: '白阿塞',
    element: 'Metal',
    elementCN: '金',
    chakra: '顶轮',
    keywords: ['纯净', '平衡', '清晰'],
    description: '属于隐晶质石英，其冰裂与彩虹，是光照进的地方。契合金属性的精准与纯净，平衡身体能量，带来内外和谐的清明状态。',
    price: 128,
    image_url: '/images/crystals/金/白阿塞珠子特写.png',
    size_mm: 10,
    stock: 40,
  },
];

/** 按五行中文筛选水晶 */
function getCrystalsByElement(elementCN) {
  const elementMap = { '木': 'Wood', '火': 'Fire', '土': 'Earth', '金': 'Metal', '水': 'Water' };
  const elementEN = elementMap[elementCN] || elementCN;
  return CRYSTAL_DB.filter(c => c.element === elementEN || c.elementCN === elementCN);
}

/** 按 ID 获取水晶 */
function getCrystalById(id) {
  return CRYSTAL_DB.find(c => c.id === id) || null;
}

/** 获取全部水晶 */
function getAllCrystals() {
  return CRYSTAL_DB;
}

module.exports = {
  CRYSTAL_DB,
  getCrystalsByElement,
  getCrystalById,
  getAllCrystals,
};
